### ISSUE TITLE
1.5 -> 1.6 upgrade fails due to invalid CRD spec

### ISSUE THREAD

**Issue by treyhyde** [knative/operator#1131] opened 2022-07-18 20:50 UTC
**Describe the bug**
When applying the vanilla operator 1.6 manifest over an existing operator 1.5 install,

```Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "knativeeventings.operator.knative.dev", Namespace: ""
for: "./infrastructure/cluster-base/kn-operator.yaml": CustomResourceDefinition.apiextensions.k8s.io "knativeeventings.operator.knative.dev" is invalid: [spec.conversion.webhookClientConfig: Forbidden: should not be set when strategy is not set to Webhook, spec.conversion.conversionReviewVersions: Forbidden: should not be set when strategy is not set to Webhook, status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions]```

Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "knativeservings.operator.knative.dev", Namespace: ""
for: "./infrastructure/cluster-base/kn-operator.yaml": CustomResourceDefinition.apiextensions.k8s.io "knativeservings.operator.knative.dev" is invalid: [spec.conversion.webhookClientConfig: Forbidden: should not be set when strategy is not set to Webhook, spec.conversion.conversionReviewVersions: Forbidden: should not be set when strategy is not set to Webhook, status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions]
```

Kube 1.22
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**Expected behavior**
1.6 applies cleanly

**To Reproduce**
kubectl apply -f release manifests.

**Knative release version**
Existing: 1.5.1
Attempting 1.6

**Comment by houshengbo** [comment] 2022-07-20 14:52
@treyhyde Could you share us the content of your existing serving and eventing crs? You can run 
```
kubectl get knativeserving -n knative-serving -o yaml
```
And the content of your crds, by running
```
kubectl get crd knativeservings.operator.knative.dev -oyaml
```

**Comment by houshengbo** [comment] 2022-07-20 16:04
You need to transition all the existing CRs into the v1beta1 version by running:
```
kubectl create -f https://github.com/knative/operator/releases/download/knative-v1.5.1/operator-post-install.yaml
```
You need to wait for several minutes for the transition to finish.

Another way to force the transition is to re-apply your existing CRs again by changing "/v1alpha1" into "/v1beta1" in the APIVersion.

After the existing CRs are in v1beta1 version, you should be able to upgrade from 1.5 to 1.6.

**Comment by treyhyde** [comment] 2022-07-20 16:47
ah yes, those post-installs are tricky.  Something you would expect the operator to do and also something that is really tough in gitops.   Manual intervention.



```{"severity":"INFO","timestamp":"2022-07-20T16:45:26.890480196Z","caller":"logging/config.go:80","message":"Fetch GitHub commit ID from kodata failed","error":"open /var/run/ko/HEAD: no such file or directory"}
{"severity":"INFO","timestamp":"2022-07-20T16:45:26.891947444Z","logger":"storage-migrator","caller":"migrate/main.go:69","message":"Migrating 2 group resources"}
{"severity":"INFO","timestamp":"2022-07-20T16:45:26.893146111Z","logger":"storage-migrator","caller":"migrate/main.go:72","message":"Migrating group resource knativeservings.operator.knative.dev"}
{"severity":"EMERGENCY","timestamp":"2022-07-20T16:45:56.895753089Z","logger":"storage-migrator","caller":"migrate/main.go:78","message":"Failed to migrate: unable to fetch crd knativeservings.operator.knative.dev - Get \"https://172.20.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/knativeservings.operator.knative.dev\": dial tcp 172.20.0.1:443: i/o timeout","stacktrace":"main.main\n\tknative.dev/pkg@v0.0.0-20220601013938-bac16f2394ce/apiextensions/storageversion/cmd/migrate/main.go:78\nruntime.main\n\truntime/proc.go:250"}```

**Comment by treyhyde** [comment] 2022-07-20 17:23
Serving gist, after 1.5.1 post-install

https://gist.github.com/treyhyde/9db65baf0eb46d6824bd00fb9fd1e61e

**Comment by houshengbo** [comment] 2022-07-21 15:38
What happened to me is that if I did not run the post-install scripts, I ran into the same issue as you had.
After I ran the post install scripts, the 1.6 knative operator would be installed fine, but when I checked on the CRs with
```
kubectl get knativeserving -n knative-serving
```
it would report issues on `v1alpha1`, which DID NOT happen last year in 2021.(I got surprised by this situation, and am looking around to see if anyone knows it better.)

To resolve this issue, you probably need to re-apply your existing serving and eventing CRs by changing the version into `v1beta1` in the APIVersion to get thru.

**Comment by houshengbo** [comment] 2022-07-27 15:54
I will close this issue.
Reopen it if the above solution does not work for you.

**Comment by treyhyde** [comment] 2022-07-30 00:43
I don't have permission to reopen it, but removing the .kube/cache does not help.

**Comment by treyhyde** [comment] 2022-07-30 00:44
```Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "knativeservings.operator.knative.dev", Namespace: ""
for: "./infrastructure/cluster-base/kn-operator.yaml": CustomResourceDefinition.apiextensions.k8s.io "knativeservings.operator.knative.dev" is invalid: [spec.conversion.webhookClientConfig: Forbidden: should not be set when strategy is not set to Webhook, spec.conversion.conversionReviewVersions: Forbidden: should not be set when strategy is not set to Webhook]```

**Comment by tshak** [comment] 2022-08-08 12:18
Thank Vincent! I reviewed the PR. I’m not sure that upgrading the CRs from v1alpha1->v1beta1 fixes #1131 as in both cases the error occurred even though the CR was already upgraded to v1beta1.  I was assuming (potentially incorrectly) that the cause of this bug was due to old operator managed references to v1alpha1 that needed to be deleted, not due to user managed custom resources (e.g. a KnativeServing resource).  If you believe that you have a solid repro of the issue and that this PR fixes it then that's great. If not I may have some cycles to try and reproduce and verify in an isolated environment if you believe that would be beneficial. 

P.S. In a GitOps environment mutating a user managed resource (e.g. upgrading KnativerServing from v1alpha1->v1beta1) will cause configuration drift and as such the GitOps controller will re-apply the old v1alpha1. This of course can be worked around by updating the version in the git repo which should be done anyway since v1alpha1 id deprecated. The general rule that I try to follow with controllers is only to mutate resources that the controller owns and not to mutate user managed resources.

**Comment by houshengbo** [comment] 2022-08-09 13:09
@tshak You can try to install https://github.com/knative/operator/releases/tag/knative-v1.5.2 to see how it goes. If everything seems fine: operator is running, CRs are running good, knative components are running fine, etc, install the https://github.com/knative/operator/releases/tag/knative-v1.6.0.

**Comment by tshak** [comment] 2022-08-09 13:33
Good news! I have upgraded to `v1.5.2` and it looks like the `storedVersions` are in fact set to only `v1beta1`. As such I believe that I am mistaken and this fix should work (I guess that I'm confused about how `storedVersions` in a CRD is updated). I should be able to rollout to all clusters today and then re-test the upgrade to `v1.6.0`.

**Comment by tshak** [comment] 2022-08-10 08:55
I have attempted to upgrade to Operator `v1.6.0` after finishing our rollout of `v1.5.2`. I am still receiving the following error:

```
Invalid, error: [CustomResourceDefinition.apiextensions.k8s.io](http://customresourcedefinition.apiextensions.k8s.io/) "knativeeventings.operator.knative.dev" is invalid: spec.conversion.webhookClientConfig: Forbidden: should not be set when strategy is not set to Webhook
```

Note that the error is only for `KnativeEventing`. We do not have any instance of `KnativeEventing` configured. I have verified that only `v1beta` exists in the CRD's `status.storedVersions` field.

**Comment by houshengbo** [comment] 2022-08-10 14:09
@tshak Is KnativeServing CRD and CR upgraded correctly? In 1.6.0, the `spec.conversion.webhookClientConfig` for both serving and eventing CRDs are set to None.
It should be set to None, when you install the CRDs of 1.6.0. Could you check `spec.conversion.webhookClientConfig` for both serving and eveting CRDs? Check if there is any difference between them.

**Comment by tshak** [comment] 2022-08-10 14:18
Operator `1.5.2`: `spec.conversion.strategy` is set to `Webhook` for both.
Operator `1.6.0` is unable to apply as the dry-run fails with the aforementioned error.

**Comment by houshengbo** [comment] 2022-08-10 14:28
Operator 1.5.2 is good as expected, but I can upgrade to 1.6.0 without error. The CRDs have their `spec.conversion.strategy` set to none.
What is your kubenernetes version? What kubenernetes are you using?

**Comment by zacheryph** [comment] 2022-08-11 13:25
I receive this error as well. I have upgraded to 1.5.2 and ran the operator-post-install and received the same messages above from it. Neither my KnativeServing nor KnativeEventing CRs show a status.storageversion. They are both `v1beta1` (and have been.)

I am running K8s 1.24.3.

**Closed** 2022-08-11 20:41 UTC
Labels: kind/bug
